<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/2%EB%B2%88%EC%A7%B8_%EA%B0%95%EC%9D%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 제어문

**조건문**

**반복문**

# 함수

# CLASS

# Numpy

In [1]:
import numpy as np
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [2]:
type(data)

numpy.ndarray

In [3]:
data1 = [1,2,3,4,5]
type(data1)

list

In [5]:
data.ndim #차원 확인

1

In [7]:
data2 = np.array([[1,2,3],[4,5,6]])
data2.ndim

2

In [11]:
data.shape #크기 확인(?행?열)

(5,)

In [12]:
data2.shape

(2, 3)

In [14]:
data2.dtype #어떤 타입의 변수가 들어가 있나

dtype('int64')

In [16]:
data2 = data2.astype('float') #타입 변경
data2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
data2.size

6

In [18]:
data2.shape

(2, 3)

In [19]:
data = np.zeros((3,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
data = np.ones((5,3))
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
data = np.full((5,3),fill_value=10)
data

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
data = np.eye(3)
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
data = np.arange(1,10)
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
data = np.array([[1,2,3],[4,5,6]])
data1 = np.array([[10,20,30],[40,50,60]])

data+data1

array([[11, 22, 33],
       [44, 55, 66]])

In [29]:
data - data1

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [30]:
data*data2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
data.sum()

21

In [32]:
data.sum(axis=0) #열의 합계(아래로 더하기)

array([5, 7, 9])

In [35]:
data.mean(axis=0)

array([2.5, 3.5, 4.5])

In [36]:
data.var()

2.9166666666666665

In [37]:
data.max()

6

In [38]:
data.std()

1.707825127659933

In [39]:
data.min()

1

In [51]:
f = open('data.txt','r')

text = f.readlines()

np_text = np.array([])
print(text)

f.close()

['20,97,66,0,1,52,18,6,20,21,17,33,16,4,98,46,33,80,64,72,70,27,68,70,13,36,60,56,47,27,2,70,27,67,80,54,13,64,55,46,41,19,63,14,79,4,22,7,81,26,36,95,75,47,28,76,84,27,90,16,33,90,20,87,29,84,66,98,18,62,40,23,97,4,80,8,20,36,41,87,79,12,81,51,29,78,39,32,84,59,7,48,26,83,46,34,38,63,69,10,']


In [52]:
len(text)

1

In [53]:
text[0]

'20,97,66,0,1,52,18,6,20,21,17,33,16,4,98,46,33,80,64,72,70,27,68,70,13,36,60,56,47,27,2,70,27,67,80,54,13,64,55,46,41,19,63,14,79,4,22,7,81,26,36,95,75,47,28,76,84,27,90,16,33,90,20,87,29,84,66,98,18,62,40,23,97,4,80,8,20,36,41,87,79,12,81,51,29,78,39,32,84,59,7,48,26,83,46,34,38,63,69,10,'

In [54]:
text[0].split(',')

['20',
 '97',
 '66',
 '0',
 '1',
 '52',
 '18',
 '6',
 '20',
 '21',
 '17',
 '33',
 '16',
 '4',
 '98',
 '46',
 '33',
 '80',
 '64',
 '72',
 '70',
 '27',
 '68',
 '70',
 '13',
 '36',
 '60',
 '56',
 '47',
 '27',
 '2',
 '70',
 '27',
 '67',
 '80',
 '54',
 '13',
 '64',
 '55',
 '46',
 '41',
 '19',
 '63',
 '14',
 '79',
 '4',
 '22',
 '7',
 '81',
 '26',
 '36',
 '95',
 '75',
 '47',
 '28',
 '76',
 '84',
 '27',
 '90',
 '16',
 '33',
 '90',
 '20',
 '87',
 '29',
 '84',
 '66',
 '98',
 '18',
 '62',
 '40',
 '23',
 '97',
 '4',
 '80',
 '8',
 '20',
 '36',
 '41',
 '87',
 '79',
 '12',
 '81',
 '51',
 '29',
 '78',
 '39',
 '32',
 '84',
 '59',
 '7',
 '48',
 '26',
 '83',
 '46',
 '34',
 '38',
 '63',
 '69',
 '10',
 '']

In [68]:
np_text = np.array(text[0].split(','))
np_text

array(['20', '97', '66', '0', '1', '52', '18', '6', '20', '21', '17',
       '33', '16', '4', '98', '46', '33', '80', '64', '72', '70', '27',
       '68', '70', '13', '36', '60', '56', '47', '27', '2', '70', '27',
       '67', '80', '54', '13', '64', '55', '46', '41', '19', '63', '14',
       '79', '4', '22', '7', '81', '26', '36', '95', '75', '47', '28',
       '76', '84', '27', '90', '16', '33', '90', '20', '87', '29', '84',
       '66', '98', '18', '62', '40', '23', '97', '4', '80', '8', '20',
       '36', '41', '87', '79', '12', '81', '51', '29', '78', '39', '32',
       '84', '59', '7', '48', '26', '83', '46', '34', '38', '63', '69',
       '10', ''], dtype='<U2')

In [70]:
np_text2 = np_text[0:-1]
np_text2

array(['20', '97', '66', '0', '1', '52', '18', '6', '20', '21', '17',
       '33', '16', '4', '98', '46', '33', '80', '64', '72', '70', '27',
       '68', '70', '13', '36', '60', '56', '47', '27', '2', '70', '27',
       '67', '80', '54', '13', '64', '55', '46', '41', '19', '63', '14',
       '79', '4', '22', '7', '81', '26', '36', '95', '75', '47', '28',
       '76', '84', '27', '90', '16', '33', '90', '20', '87', '29', '84',
       '66', '98', '18', '62', '40', '23', '97', '4', '80', '8', '20',
       '36', '41', '87', '79', '12', '81', '51', '29', '78', '39', '32',
       '84', '59', '7', '48', '26', '83', '46', '34', '38', '63', '69',
       '10'], dtype='<U2')

In [71]:
np_text2 = np_text2.astype('int')
np_text2

array([20, 97, 66,  0,  1, 52, 18,  6, 20, 21, 17, 33, 16,  4, 98, 46, 33,
       80, 64, 72, 70, 27, 68, 70, 13, 36, 60, 56, 47, 27,  2, 70, 27, 67,
       80, 54, 13, 64, 55, 46, 41, 19, 63, 14, 79,  4, 22,  7, 81, 26, 36,
       95, 75, 47, 28, 76, 84, 27, 90, 16, 33, 90, 20, 87, 29, 84, 66, 98,
       18, 62, 40, 23, 97,  4, 80,  8, 20, 36, 41, 87, 79, 12, 81, 51, 29,
       78, 39, 32, 84, 59,  7, 48, 26, 83, 46, 34, 38, 63, 69, 10])

In [73]:
f = open('data_week.txt','r')

text = f.readlines()
print(text)

f.close()

['40,52,11,95,52,61,21\n', '53,17,83,34,29,95,51\n', '3,2,3,35,62,8,42\n', '30,10,8,5,39,49,82\n']


In [81]:
result = []
for i in text:
    i = i.strip()
    i = i.split(',')
    result.append(i)

result

[['40', '52', '11', '95', '52', '61', '21'],
 ['53', '17', '83', '34', '29', '95', '51'],
 ['3', '2', '3', '35', '62', '8', '42'],
 ['30', '10', '8', '5', '39', '49', '82']]

In [82]:
result = np.array(result,dtype='int')
result

array([[40, 52, 11, 95, 52, 61, 21],
       [53, 17, 83, 34, 29, 95, 51],
       [ 3,  2,  3, 35, 62,  8, 42],
       [30, 10,  8,  5, 39, 49, 82]])

In [83]:
result.mean(axis=1) #각주의 평균

array([47.42857143, 51.71428571, 22.14285714, 31.85714286])

In [84]:
result.mean(axis=0) #요일별 평균

array([31.5 , 20.25, 26.25, 42.25, 45.5 , 53.25, 49.  ])

# Pandas

In [85]:
import pandas as pd

In [87]:
data = pd.Series(np.array([1,2,3,4,5]))
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [88]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [89]:
data.values

array([1, 2, 3, 4, 5])

In [90]:
data.dtype

dtype('int64')

In [95]:
data = pd.Series([1,2,3],index=['강남','노원','서초'])
data1 = pd.Series([4,5,6],index=['강남','마포','동작'])

total = data+data1
total

강남    5.0
노원    NaN
동작    NaN
마포    NaN
서초    NaN
dtype: float64

In [96]:
total.fillna(0) #빈곳에 원하는것 체우기
total.dropna() #빈곳 제거

강남    5.0
dtype: float64

In [99]:
total.describe() #습관적으로 확인하기 -> 이후로 전처리 어떤식으로 할지 생각

count    1.0
mean     5.0
std      NaN
min      5.0
25%      5.0
50%      5.0
75%      5.0
max      5.0
dtype: float64

In [104]:
df = pd.read_csv('cdata.csv', encoding="cp949")
df.head()

Unnamed: 0  Index   No  Age City
0           0      1  홍길동   25   서울
1           1      2  김준기   21   서울
2           2      9  이명식   22   부산
3           3     32  방준혁   24   광주
4           4     47  최명기   31   부산

In [105]:
df.describe()

Unnamed: 0      Index        Age
count    5.000000   5.000000   5.000000
mean     2.000000  18.200000  24.600000
std      1.581139  20.388722   3.911521
min      0.000000   1.000000  21.000000
25%      1.000000   2.000000  22.000000
50%      2.000000   9.000000  24.000000
75%      3.000000  32.000000  25.000000
max      4.000000  47.000000  31.000000

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5 non-null      int64 
 1   Index       5 non-null      int64 
 2   No          5 non-null      object
 3   Age         5 non-null      int64 
 4   City        5 non-null      object
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes


In [112]:
df = pd.read_csv('cdata_nohead.csv') #header가 없음
df

0   1  홍길동  25  서울
0  1   2  김준기  21  서울
1  2   9  이명식  22  부산
2  3  32  방준혁  24  광주
3  4  47  최명기  31  부산

In [114]:
df = pd.read_csv('cdata_nohead.csv', header=None)
df.columns = ['index', 'no','이름', '나이', '지역']
df

index  no   이름  나이  지역
0      0   1  홍길동  25  서울
1      1   2  김준기  21  서울
2      2   9  이명식  22  부산
3      3  32  방준혁  24  광주
4      4  47  최명기  31  부산

In [116]:
df = pd.read_csv('cdata_nohead.csv', header=None,
                 names = ['index', 'no','이름', '나이', '지역'],
                 index_col = 'index')
df

no   이름  나이  지역
index                 
0       1  홍길동  25  서울
1       2  김준기  21  서울
2       9  이명식  22  부산
3      32  방준혁  24  광주
4      47  최명기  31  부산

*DataFrame 예제*

- 자동차 회사의 연비 데이터 파일 분석

    1. 몇 개의 회사데이터가 있는가?
    2. 회사별로 참여한 자동차가 몇대인가?(현대:20, 도요타:30....)
    3. 도심연비와 고속도로 연비를 평균내 total 연비를 구하시오.
    4. total 연비 상위 10개 회사의 회사별 개수를 구하시오.
    5. 평균 total 연비보다 높은 자동차는 PASS, 낮은 자동차는 FAIL로 구분하세요.
    6. PASS 자동차 대수와 FAIL 자동차 대수를 구하시오.

In [117]:
data = pd.read_csv('mpg.csv')
data.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [123]:
data.describe()

displ         year         cyl         cty         hwy
count  234.000000   234.000000  234.000000  234.000000  234.000000
mean     3.471795  2003.500000    5.888889   16.858974   23.440171
std      1.291959     4.509646    1.611534    4.255946    5.954643
min      1.600000  1999.000000    4.000000    9.000000   12.000000
25%      2.400000  1999.000000    4.000000   14.000000   18.000000
50%      3.300000  2003.500000    6.000000   17.000000   24.000000
75%      4.600000  2008.000000    8.000000   19.000000   27.000000
max      7.000000  2008.000000    8.000000   35.000000   44.000000

In [122]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   manufacturer  234 non-null    object 
 1   model         234 non-null    object 
 2   displ         234 non-null    float64
 3   year          234 non-null    int64  
 4   cyl           234 non-null    int64  
 5   trans         234 non-null    object 
 6   drv           234 non-null    object 
 7   cty           234 non-null    int64  
 8   hwy           234 non-null    int64  
 9   fl            234 non-null    object 
 10  category      234 non-null    object 
dtypes: float64(1), int64(4), object(6)
memory usage: 20.2+ KB


In [121]:
data.tail()

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

    category  
229  midsize  
230  midsize  
231  midsize  
232  midsize  
233  midsize

In [124]:
data.isnull().sum() #각 컬럼의 결측치 데이터확인

manufacturer    0
model           0
displ           0
year            0
cyl             0
trans           0
drv             0
cty             0
hwy             0
fl              0
category        0
dtype: int64

In [131]:
data['manufacturer'].describe()

count       234
unique       15
top       dodge
freq         37
Name: manufacturer, dtype: object

In [128]:
# 1. 몇 개의 회사데이터가 있는가?

data['manufacturer'].unique() # 참여한 회사 이름 -> 총 15개 회사 존재

array(['audi', 'chevrolet', 'dodge', 'ford', 'honda', 'hyundai', 'jeep',
       'land rover', 'lincoln', 'mercury', 'nissan', 'pontiac', 'subaru',
       'toyota', 'volkswagen'], dtype=object)

In [130]:
# 2. 회사별로 참여한 자동차가 몇대인가?(현대:20, 도요타:30....)

data['manufacturer'].value_counts() # 각 회사의 자동차 수

dodge         37
toyota        34
volkswagen    27
ford          25
chevrolet     19
audi          18
hyundai       14
subaru        14
nissan        13
honda          9
jeep           8
pontiac        5
land rover     4
mercury        4
lincoln        3
Name: manufacturer, dtype: int64

In [132]:
# 3. 도심연비와 고속도로 연비를 평균내 total 연비를 구하시오.

data['total'] = (data['cty'] + data['hwy'])/2
data

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
0           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
1           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
2           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
3           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
4           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

    category  total  
0    compact   23.5  
1    compact   25.0  
2    compact   25.5  
3    compact   25.5  
4    compact   21.0  
..       ...    ...  
229  midsize   23.5  
230  midsize   25.0  
231  midsize   21.0  
232  midsize   22.0  
233  midsize   21.5  

[234 rows x 12 columns]

In [135]:
# 4. total 연비 상위 10개 회사의 회사별 개수를 구하시오.

data10 = data.sort_values(by='total', ascending=False)
data10.head(10)

manufacturer       model  displ  year  cyl       trans drv  cty  hwy fl  \
221   volkswagen  new beetle    1.9  1999    4  manual(m5)   f   35   44  d   
212   volkswagen       jetta    1.9  1999    4  manual(m5)   f   33   44  d   
222   volkswagen  new beetle    1.9  1999    4    auto(l4)   f   29   41  d   
196       toyota     corolla    1.8  2008    4  manual(m5)   f   28   37  r   
195       toyota     corolla    1.8  1999    4  manual(m5)   f   26   35  r   
105        honda       civic    1.8  2008    4    auto(l5)   f   25   36  r   
99         honda       civic    1.6  1999    4  manual(m5)   f   28   33  r   
197       toyota     corolla    1.8  2008    4    auto(l4)   f   26   35  r   
104        honda       civic    1.8  2008    4  manual(m5)   f   26   34  r   
106        honda       civic    1.8  2008    4    auto(l5)   f   24   36  c   

       category  total  
221  subcompact   39.5  
212     compact   38.5  
222  subcompact   35.0  
196     compact   32.5  
195     compact   30.5  
105  subcompact   30.5  
99   subcompact   30.5  
197     compact   30.5  
104  subcompact   30.0  
106  subcompact   30.0

In [137]:
# 현대 자동차의 평균 연비
data[data['manufacturer'] == 'hyundai']

manufacturer    model  displ  year  cyl       trans drv  cty  hwy fl  \
108      hyundai   sonata    2.4  1999    4    auto(l4)   f   18   26  r   
109      hyundai   sonata    2.4  1999    4  manual(m5)   f   18   27  r   
110      hyundai   sonata    2.4  2008    4    auto(l4)   f   21   30  r   
111      hyundai   sonata    2.4  2008    4  manual(m5)   f   21   31  r   
112      hyundai   sonata    2.5  1999    6    auto(l4)   f   18   26  r   
113      hyundai   sonata    2.5  1999    6  manual(m5)   f   18   26  r   
114      hyundai   sonata    3.3  2008    6    auto(l5)   f   19   28  r   
115      hyundai  tiburon    2.0  1999    4    auto(l4)   f   19   26  r   
116      hyundai  tiburon    2.0  1999    4  manual(m5)   f   19   29  r   
117      hyundai  tiburon    2.0  2008    4  manual(m5)   f   20   28  r   
118      hyundai  tiburon    2.0  2008    4    auto(l4)   f   20   27  r   
119      hyundai  tiburon    2.7  2008    6    auto(l4)   f   17   24  r   
120      hyundai  tiburon    2.7  2008    6  manual(m6)   f   16   24  r   
121      hyundai  tiburon    2.7  2008    6  manual(m5)   f   17   24  r   

       category  total  
108     midsize   22.0  
109     midsize   22.5  
110     midsize   25.5  
111     midsize   26.0  
112     midsize   22.0  
113     midsize   22.0  
114     midsize   23.5  
115  subcompact   22.5  
116  subcompact   24.0  
117  subcompact   24.0  
118  subcompact   23.5  
119  subcompact   20.5  
120  subcompact   20.0  
121  subcompact   20.5

In [138]:
data[data['manufacturer'] == 'hyundai']['total']

108    22.0
109    22.5
110    25.5
111    26.0
112    22.0
113    22.0
114    23.5
115    22.5
116    24.0
117    24.0
118    23.5
119    20.5
120    20.0
121    20.5
Name: total, dtype: float64

In [139]:
data[data['manufacturer'] == 'hyundai']['total'].mean()

22.75

In [140]:
# 5. 평균 total 연비보다 높은 자동차는 PASS, 낮은 자동차는 FAIL로 구분하세요.

data['pass'] = np.where(data['total']>=data['total'].mean(), 'PASS', 'FAIL') #np.where(조건,성공시,실패시)
data

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
0           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
1           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
2           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
3           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
4           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
229   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
230   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
231   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
232   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
233   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

    category  total  pass  
0    compact   23.5  PASS  
1    compact   25.0  PASS  
2    compact   25.5  PASS  
3    compact   25.5  PASS  
4    compact   21.0  PASS  
..       ...    ...   ...  
229  midsize   23.5  PASS  
230  midsize   25.0  PASS  
231  midsize   21.0  PASS  
232  midsize   22.0  PASS  
233  midsize   21.5  PASS  

[234 rows x 13 columns]

In [145]:
# 6. PASS 자동차 대수와 FAIL 자동차 대수를 구하시오.

data['pass'].value_counts()

PASS    123
FAIL    111
Name: pass, dtype: int64

In [146]:
# 전체 자동차 중에서 어느 회사의 기술력이 좋은가? pass중에서 가장 많이 포함된 회사는 무엇인가?

data[data['pass']=='PASS']['manufacturer'].value_counts()

volkswagen    26
toyota        19
audi          14
subaru        14
hyundai       13
honda          9
nissan         9
chevrolet      7
pontiac        5
dodge          4
ford           3
Name: manufacturer, dtype: int64

# 시각화

다음 파일에 계속~~~