<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/Lecture_PCA_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
app=np.array([8,10,9,7,6,3,2,4,6,2,8,7])
per=np.array([1,7,9,5,4,5,1,2,4,5,6,7])

In [3]:
data=np.array([app,per])
data=data.T
data

array([[ 8,  1],
       [10,  7],
       [ 9,  9],
       [ 7,  5],
       [ 6,  4],
       [ 3,  5],
       [ 2,  1],
       [ 4,  2],
       [ 6,  4],
       [ 2,  5],
       [ 8,  6],
       [ 7,  7]])

In [4]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
data_scaled=ss.fit_transform(data)
data_scaled

array([[ 0.77459667, -1.55563492],
       [ 1.54919334,  0.98994949],
       [ 1.161895  ,  1.83847763],
       [ 0.38729833,  0.14142136],
       [ 0.        , -0.28284271],
       [-1.161895  ,  0.14142136],
       [-1.54919334, -1.55563492],
       [-0.77459667, -1.13137085],
       [ 0.        , -0.28284271],
       [-1.54919334,  0.14142136],
       [ 0.77459667,  0.56568542],
       [ 0.38729833,  0.98994949]])

In [5]:
cov=np.cov(data_scaled.T)
cov

array([[1.09090909, 0.56763974],
       [0.56763974, 1.09090909]])

In [6]:
eig_value, eig_vector=np.linalg.eig(cov) # 큰 값을 사용하니 1번 -> 1.6585 값을 사용
eig_value

array([0.52326935, 1.65854883])

In [7]:
eig_value[1]/(eig_value[0]+eig_value[1]) #차원 축소(압축)를 했을때 데이터가 76퍼 보존된다.

0.7601682148149539

In [8]:
eig_value[1]

1.658548832323536

In [9]:
eig_vector # 0행 벡터 , 1행 벡터

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [11]:
eig_vector[1] #value 큰 값만 사용하니 벡터도 1행을 사용

array([ 0.70710678, -0.70710678])

In [12]:
favor=data_scaled.dot(eig_vector[1]) # 벡터의 내적을 구하면 차원이 축소됨
favor

array([ 1.64772256,  0.39544512, -0.47841616,  0.17386128,  0.2       ,
       -0.92158384,  0.00455488,  0.25227744,  0.2       , -1.19544512,
        0.14772256, -0.42613872])

In [ ]:
data

array([[ 8,  1],
       [10,  7],
       [ 9,  9],
       [ 7,  5],
       [ 6,  4],
       [ 3,  5],
       [ 2,  1],
       [ 4,  2],
       [ 6,  4],
       [ 2,  5],
       [ 8,  6],
       [ 7,  7]])

In [ ]:
John=np.array([3,9])
Tom=np.array([5,2])

In [ ]:
John.reshape(-1,1)

array([[3],
       [9]])

In [ ]:
John_scaled=(John-np.mean(data))/np.std(data)
John_scaled

array([-0.91132238,  1.43207802])

In [ ]:
John_favor=John_scaled.dot(eig_vector[1].T)
John_favor

-1.657034312216982

In [ ]:
Tom_scaled=(Tom-np.mean(data))/np.std(data)
Tom_scaled

array([-0.13018891, -1.30188911])

In [ ]:
Tom_favor=Tom_scaled.dot(eig_vector[1].T)
Tom_favor

0.8285171561084912