<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.22.4'

In [ ]:
data = np.array([1,2,3])
data1 = np.array([[1,2,3],[4,5,6]])

In [ ]:
type(data)

numpy.ndarray

In [ ]:
type(data1)

numpy.ndarray

In [ ]:
data.ndim

1

In [ ]:
data1.ndim

2

In [ ]:
data.shape

(3,)

In [ ]:
data.dtype

dtype('int64')

In [ ]:
data = np.array([1,2,3], dtype='float')

In [ ]:
data.dtype

dtype('float64')

In [ ]:
data.size

3

In [ ]:
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data

array([1., 2., 3.])

In [ ]:
data.shape

(3,)

In [ ]:
print(data.T)

[1. 2. 3.]


In [ ]:
print(data1)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(data1.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
data = np.aragne(0,10,3)

AttributeError: ignored

In [ ]:
data = np.arange(0,10,3)
print(data)

[0 3 6 9]


In [ ]:
data = np.linspace(0,10,3)
print(data)

[ 0.  5. 10.]


In [ ]:
data = np.eye(3)

In [ ]:
np.shape(data)

(3, 3)

In [ ]:
np.zeros(shape=(4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full(shape=(2,3), fill_value=10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.random.randn(10)

array([ 0.44747511,  0.18946617, -0.76132849, -1.03474366,  0.59767698,
        0.38250767,  0.32761694,  0.49735842,  1.17303573,  2.12738356])

In [ ]:
np.random.randint(6)

4

In [ ]:
np.random.randint(6)

2

In [ ]:
np.random.rand(6)

array([0.88576391, 0.35882952, 0.59168341, 0.47982584, 0.81660501,
       0.51541733])

In [ ]:
data = np.array([1,2,3,4,5,6,7,8,9])
data.shape

(9,)

In [ ]:
result =data.reshape(3,3)

In [ ]:
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
data1 = np.array([[1,2],[3,4]])
data2 = np.array([[10,20],[30,40]])

data1+data2

array([[11, 22],
       [33, 44]])

In [ ]:
data1-data2

array([[ -9, -18],
       [-27, -36]])

In [ ]:
data1*data2

array([[ 10,  40],
       [ 90, 160]])

In [ ]:
data1/data2

array([[0.1, 0.1],
       [0.1, 0.1]])

In [ ]:
data = np.array([[1,2,3],[10,20,30]])
data.sum()

66

In [ ]:
print(data)

[[ 1  2  3]
 [10 20 30]]


In [ ]:
data.sum(axis=0)

array([11, 22, 33])

In [ ]:
data.mean()

11.0

In [ ]:
data.max()

30

In [ ]:
data.mean(axis=0)

array([ 5.5, 11. , 16.5])

In [ ]:
data.min()

1

In [ ]:
data.var()

114.66666666666667