<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/pytorch_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.0.0+cu118


In [3]:
data =torch.empty(3,5)
data

tensor([[-8.0990e-15,  4.5901e-41, -2.8332e-32,  4.5901e-41, -2.8353e-32],
        [ 4.5901e-41, -2.8552e-32,  4.5901e-41, -2.8538e-32,  4.5901e-41],
        [-2.8512e-32,  4.5901e-41, -2.8516e-32,  4.5901e-41, -2.7793e-32]])

In [4]:
data = torch.rand(3,5)
data

tensor([[0.4048, 0.5169, 0.1430, 0.3216, 0.3060],
        [0.7143, 0.8709, 0.1403, 0.7315, 0.3279],
        [0.4944, 0.5917, 0.0260, 0.0743, 0.8553]])

In [5]:
data = torch.zeros(3,5)
data

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
data = torch.ones(3,5)
data

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [7]:
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [8]:
data= torch.tensor([[1,2,3],[10,20,30]])
data

tensor([[ 1,  2,  3],
        [10, 20, 30]])

In [9]:
data = torch.zeros(4,2,dtype=torch.long)
data

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [10]:
data1 = torch.randn_like(data,dtype=torch.float)
data1

tensor([[-0.2171, -1.4747],
        [ 1.5888,  1.0119],
        [-2.5445,  0.3396],
        [-2.2300,  0.2318]])

In [11]:
data1.dtype

torch.float32

In [12]:
data = torch.FloatTensor([1,2,3])
data

tensor([1., 2., 3.])

In [13]:
data.dtype

torch.float32

In [14]:
data = torch.IntTensor([1,2,3])
data

tensor([1, 2, 3], dtype=torch.int32)

In [15]:
data1 = data.float()
data1.dtype

torch.float32

In [17]:
'cuda' if torch.cuda.is_available() else 'cpu'

'cpu'

In [2]:
'cuda' if torch.cuda.is_available() else 'cpu'

'cuda'

In [3]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [4]:
data = torch.ones(3,3,device=device)
data

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [5]:
data1 = torch.ones(3,3,device=device)
data1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [7]:
data2 = torch.ones(3,3)
data2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
data + data1 #쿠다끼리라서 계산 가능

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

In [9]:
data1 + data2#서로 디바이스가 달라서 불가능

RuntimeError: ignored

In [10]:
data2 = data2.to(device) #디바이스 쿠다로 변경
data2

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [11]:
data1 + data2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0')

In [13]:
data = torch.tensor(0)
print(data)
print(data.ndim) #차원
print(data.shape)

tensor(0)
0
torch.Size([])


In [14]:
data = torch.tensor([1,2,3])
print(data)
print(data.ndim)
print(data.shape)

tensor([1, 2, 3])
1
torch.Size([3])


In [15]:
data = torch.tensor([[1,2,3],[1,2,3]])
print(data)
print(data.ndim)
print(data.shape)

tensor([[1, 2, 3],
        [1, 2, 3]])
2
torch.Size([2, 3])


In [16]:
data = torch.tensor([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(data)
print(data.ndim)
print(data.shape)

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]])
3
torch.Size([2, 2, 3])


In [17]:
import math

In [20]:
data = torch.rand(2,3) * 3 * -1
data

tensor([[-0.2566, -0.2239, -0.7129],
        [-2.4028, -0.1718, -1.2530]])

In [21]:
torch.abs(data)

tensor([[0.2566, 0.2239, 0.7129],
        [2.4028, 0.1718, 1.2530]])

In [23]:
torch.floor(data) #내림

tensor([[-1., -1., -1.],
        [-3., -1., -2.]])

In [24]:
torch.ceil(data) #올림

tensor([[-0., -0., -0.],
        [-2., -0., -1.]])

In [25]:
torch.clamp(data,0.2,0.5) # 최소, 최대 값 설정해주기

tensor([[0.2000, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000]])

In [26]:
torch.min(data)

tensor(-2.4028)

In [27]:
torch.max(data)

tensor(-0.1718)

In [28]:
torch.mean(data)

tensor(-0.8368)

In [29]:
torch.std(data) #편차

tensor(0.8713)

In [30]:
torch.unique(torch.tensor([1,1,1,2,2,2,1,2,3,3,4]))

tensor([1, 2, 3, 4])

In [31]:
data = torch.rand(2,3)
data

tensor([[0.1824, 0.1626, 0.5785],
        [0.7852, 0.2877, 0.0789]])

In [32]:
data.argmax(dim=0)

tensor([1, 1, 0])

In [33]:
data.argmax(dim=1)

tensor([2, 0])

In [35]:
data = torch.tensor([1,2,3,4,5])
data[3]

tensor(4)

In [36]:
data[1:3]

tensor([2, 3])

In [37]:
data = torch.tensor([[1,2,3,4,5],[10,20,30,40,50]])
data[0,0]

tensor(1)

In [38]:
data[1,0]

tensor(10)

In [39]:
data[0,1:3]

tensor([2, 3])

In [40]:
data = torch.randn(2,4)
data

tensor([[ 0.3965, -0.1817,  0.9444, -0.6694],
        [ 1.0323,  2.2756,  0.3340,  0.2391]])

In [42]:
data = data.view(8) #데이터의 사이즈에 맞춰서 숫자를 적어야함
data

tensor([ 0.3965, -0.1817,  0.9444, -0.6694,  1.0323,  2.2756,  0.3340,  0.2391])

In [43]:
data = torch.randn(2,4)
data

tensor([[ 2.9992, -0.2900,  0.6322,  0.2419],
        [ 0.8793,  0.0669, -1.2769, -0.0178]])

In [44]:
data1 = data.view(4,2)
data1

tensor([[ 2.9992, -0.2900],
        [ 0.6322,  0.2419],
        [ 0.8793,  0.0669],
        [-1.2769, -0.0178]])

In [45]:
data1 = data.view(4,-1)
data1

tensor([[ 2.9992, -0.2900],
        [ 0.6322,  0.2419],
        [ 0.8793,  0.0669],
        [-1.2769, -0.0178]])

In [46]:
data1 = data.view(-1)
data1

tensor([ 2.9992, -0.2900,  0.6322,  0.2419,  0.8793,  0.0669, -1.2769, -0.0178])

In [47]:
data = torch.randn(1,3,5)
data

tensor([[[-1.3920, -0.1663,  0.7260,  1.2433, -0.2351],
         [ 0.2458, -0.3669, -1.6001, -0.5824,  1.1751],
         [ 0.6739, -1.0063,  0.7268, -0.3966,  0.3003]]])

In [48]:
data.ndim

3

In [49]:
data.size

<function Tensor.size>

In [50]:
data.shape

torch.Size([1, 3, 5])

In [51]:
data1 = data.squeeze() #차원 축소
data1

tensor([[-1.3920, -0.1663,  0.7260,  1.2433, -0.2351],
        [ 0.2458, -0.3669, -1.6001, -0.5824,  1.1751],
        [ 0.6739, -1.0063,  0.7268, -0.3966,  0.3003]])

In [52]:
data1.ndim

2

In [53]:
data.unsqueeze(dim=0) #차원 확대

tensor([[[[-1.3920, -0.1663,  0.7260,  1.2433, -0.2351],
          [ 0.2458, -0.3669, -1.6001, -0.5824,  1.1751],
          [ 0.6739, -1.0063,  0.7268, -0.3966,  0.3003]]]])

In [55]:
data.shape

torch.Size([1, 3, 5])

In [56]:
data

tensor([[[-1.3920, -0.1663,  0.7260,  1.2433, -0.2351],
         [ 0.2458, -0.3669, -1.6001, -0.5824,  1.1751],
         [ 0.6739, -1.0063,  0.7268, -0.3966,  0.3003]]])

In [58]:
data1 = data.unsqueeze(dim=2)
data1.shape

torch.Size([1, 3, 1, 5])

In [61]:
data = torch.tensor([1,2])
data1 = torch.tensor([10,20])
torch.stack([data,data1]) # 쌓기

tensor([[ 1,  2],
        [10, 20]])

In [62]:
torch.cat([data,data1]) #결합

tensor([ 1,  2, 10, 20])

In [63]:
data = torch.randn(1,2,4)
data1 = torch.randn(1,2,4)
data2 = torch.cat([data,data1], dim=0)
data2

tensor([[[ 1.0056,  0.6918,  2.7099, -0.8609],
         [ 0.8515, -1.6589,  0.1350, -0.0097]],

        [[ 0.0793,  0.2690, -1.4965, -0.4597],
         [-1.1520, -2.6808,  1.4511, -1.4317]]])

In [64]:
data

tensor([[[ 1.0056,  0.6918,  2.7099, -0.8609],
         [ 0.8515, -1.6589,  0.1350, -0.0097]]])

In [65]:
data1

tensor([[[ 0.0793,  0.2690, -1.4965, -0.4597],
         [-1.1520, -2.6808,  1.4511, -1.4317]]])