<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
data.reshape(2,5) #1차원 데이터를 2차원으로 변경

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
data.reshape(-1,5) #열의 개수를 5개로 맞추고 행의 개수는 자동으로 배정시키기

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
data.reshape(5,-1) #행의 개수를 5개로 맞추고 열의 개수는 자동으로 배정시키기

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
data.shape

(10,)

In [10]:
data.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
#2차원 데이터를 1차원으로 변경
data = np.ravel(data)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])