<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/%EC%8B%A4%EC%8A%B501_RegressionModeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mavhine Learning with Python
## 실습01. Regression Modeling

1.   Load Data & Explore Data
2.   Preprocess Data
3.   Model Train
4.   Model Test
5.   Model Evaluate

In [1]:
# 1. Load Data & Explore Data

import pandas as pd

data = pd.read_csv('5강_데이터_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
data.describe(include='all')

R&D Spend  Administration  Marketing Spend     State  \
count       50.000000       50.000000        50.000000        50   
unique            NaN             NaN              NaN         3   
top               NaN             NaN              NaN  New York   
freq              NaN             NaN              NaN        17   
mean     73721.615600   121344.639600    211025.097800       NaN   
std      45902.256482    28017.802755    122290.310726       NaN   
min          0.000000    51283.140000         0.000000       NaN   
25%      39936.370000   103730.875000    129300.132500       NaN   
50%      73051.080000   122699.795000    212716.240000       NaN   
75%     101602.800000   144842.180000    299469.085000       NaN   
max     165349.200000   182645.560000    471784.100000       NaN   

               Profit  
count       50.000000  
unique            NaN  
top               NaN  
freq              NaN  
mean    112012.639200  
std      40306.180338  
min      14681.400000  
25%      90138.902500  
50%     107978.190000  
75%     139765.977500  
max     192261.830000

In [6]:
# 2. Preprocess Data

# 2-1. x / y 분리 (x, 영향을 미치는 독립 변수 -> R&D Spend, Administration, Marketing Spend, State)(y, label -> Profit)

#x = data[["R&D Spend", "Administration", "Marketing Spend", "State"]]
#y = data["Profit"]

# iloc[]로 가져오면 dataframe으로 가져옴
# numpy 형태로 사용하기 위해서 .values 사용
x = data.iloc[:, :-1].values #State까지
y = data.iloc[:, -1].values # Profit만
print(x[:5])
print(y[:5])

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]
[192261.83 191792.06 191050.39 182901.99 166187.94]


In [7]:
# 2-2. One hot encoding

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encofer', OneHotEncoder(), [3])],
                       remainder='passthrough')

x = ct.fit_transform(x)

print(x[:5])

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


In [8]:
# 2-3. Train/Test Split

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=9)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(40, 6)
(10, 6)
(40,)
(10,)


In [9]:
# 3. Model Train

from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

LinearRegression()

In [11]:
# 4. Model Test

y_predict = regressor.predict(x_test)
print(y_test)
print(y_predict)

[111313.02  89949.14 191050.39 132602.65  65200.33 155752.6  129917.04
 118474.03  97427.84 107404.34]
[119819.55288791  86354.20207815 183301.32209456 152445.18324335
  64875.520236   162565.65848552 148066.5713629  115726.7823929
  98775.28101685 102274.57539609]


In [15]:
# 5. Model Evaluate

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_predict)
mse = mean_squared_error(y_test, y_predict, squared=False)
r2 = r2_score(y_test, y_predict)

print(mae)
print(mse)
print(r2)

7420.492479883333
9750.205469397526
0.9153873936691637


In [19]:
# 6. 모델 확인
# y = w1x1 + w2x2 + w3x3 + ...

print(regressor.coef_) #가중치값들

[-1.29527814e+03  5.67807340e+02  7.27470804e+02  8.15623658e-01
  7.52203964e-03  2.60919967e-02]
