<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/%EC%8B%A4%EC%8A%B504_PerceptronModeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Deep Learning with PyTorch 
### 실습04. Perceptron Modeling : AND Function

1. Prepare Dataset 
2. Train Model
3. Test Model

  
<img src="https://dl.dropbox.com/s/enqqtqnegzb6ceg/and.png" width="400"/>

#### 1. Prepare Data

In [3]:
# 1-1. 데이터 준비

# tensor

import torch

X = torch.FloatTensor([[0,0], [0,1], [1,0], [1,1]])
y = torch.FloatTensor([[0], [0], [0], [1]])

print(X)
print(y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0.],
        [0.],
        [0.],
        [1.]])


In [4]:
# 1-2. 데이터 확인

print(X.shape)
print(y.shape)

torch.Size([4, 2])
torch.Size([4, 1])


#### 2. Train Model

* Design Network: 어떤 레이어, 몇층의 레이어, 각 레이어 몇 노드
* Loss Func & Optimizer
* Train Loop (Forward, back, update)

In [5]:
# 2-1. Network

import torch.nn as nn

linear = nn.Linear(2, 1) # 데이터의 개수가 아니라 하나의 샘플에 들어있는 feature
sigmoid = nn.Sigmoid() # activation func

# 순차적 계층으로 모델 정의
model = nn.Sequential(linear,
                      sigmoid)

print(model)

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
  (1): Sigmoid()
)


In [7]:
# 2-2. Loss Function & Optimizer

loss_fn = nn.BCELoss() # for binary classification
optimizer = torch.optim.SGD(model.parameters(), lr=1)


In [8]:
# 2-3. Train Loop

for step in range(100):
  output = model(X) # 모델이 계산한 값: forward propagation

  loss = loss_fn(output, y) # cost 값 계산

  optimizer.zero_grad() # gradient 0 초기화
  loss.backward() # backpropagation weight가 loss에 얼마나 영향을 끼치는지 계산
  optimizer.step() # weight update

  if step % 10 == 0:
    print(step, loss.item())

0 0.6481648087501526
10 0.42648547887802124
20 0.34044018387794495
30 0.28589701652526855
40 0.24764114618301392
50 0.21895945072174072
60 0.19646522402763367
70 0.1782522201538086
80 0.16315346956253052
90 0.15040642023086548


#### 3. Test Model

In [9]:
# 3. Test

test_tensor = torch.FloatTensor([[1,1], [1,0], [0,1]])

with torch.no_grad(): # test 진행하는 동안 gradient 연산하지 않음
  output = model(test_tensor)
  print(output)

tensor([[0.7914],
        [0.1457],
        [0.1469]])
