<a href="https://colab.research.google.com/github/audwls4545/metaverse/blob/main/%ED%95%9C%EA%B8%80%EC%A0%95%EC%88%98%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 58.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 30.3 MB/s eta 0:00:00


In [2]:
from konlpy.tag import Okt
from nltk.tokenize import word_tokenize
from collections import Counter

In [3]:
okt = Okt()

In [7]:
text_data = '''
김일두 카카오브레인 각자 대표는 “인체 비율 및 구도, 공간감과 입체감을 표현하는 투시도 등 다양한 이미지 데이터 학습 및 기술 고도화 과정을 거쳐 칼로 2.0을 선보이게 됐다”며 “많은 데이터와 사용자 피드백을 학습시켜 실사 수준의 이미지를 생성하는 동시에 보다 다양한 사용자의 니즈를 반영할 수 있는 이미지 생성 모델로 발전시켜 나갈 것”이라고 말했다
'''

In [8]:
text = okt.nouns(text_data)
text

['김일',
 '카카오',
 '브레인',
 '각자',
 '대표',
 '인체',
 '비율',
 '및',
 '구도',
 '공간',
 '감',
 '입',
 '체감',
 '표현',
 '투시도',
 '등',
 '이미지',
 '데이터',
 '학습',
 '및',
 '기술',
 '고도화',
 '과정',
 '칼',
 '며',
 '데이터',
 '사용자',
 '피드백',
 '학습',
 '실사',
 '수준',
 '이미지',
 '생',
 '동시',
 '사용자',
 '를',
 '반영',
 '수',
 '이미지',
 '생',
 '모델',
 '발전',
 '것',
 '말']

In [9]:
words_freq = Counter(text)

In [10]:
for w,c in words_freq.items():
    print(w,c)

[('김일',1)]

김일 1
카카오 1
브레인 1
각자 1
대표 1
인체 1
비율 1
및 2
구도 1
공간 1
감 1
입 1
체감 1
표현 1
투시도 1
등 1
이미지 3
데이터 2
학습 2
기술 1
고도화 1
과정 1
칼 1
며 1
사용자 2
피드백 1
실사 1
수준 1
생 2
동시 1
를 1
반영 1
수 1
모델 1
발전 1
것 1
말 1


[('김일', 1)]

In [11]:
words_cleaned = [ (w,c) for w,c in words_freq.items() if c >= 1]
words_cleaned.sort(key=lambda x: x[1], reverse=True)

In [12]:
words_cleaned

[('이미지', 3),
 ('및', 2),
 ('데이터', 2),
 ('학습', 2),
 ('사용자', 2),
 ('생', 2),
 ('김일', 1),
 ('카카오', 1),
 ('브레인', 1),
 ('각자', 1),
 ('대표', 1),
 ('인체', 1),
 ('비율', 1),
 ('구도', 1),
 ('공간', 1),
 ('감', 1),
 ('입', 1),
 ('체감', 1),
 ('표현', 1),
 ('투시도', 1),
 ('등', 1),
 ('기술', 1),
 ('고도화', 1),
 ('과정', 1),
 ('칼', 1),
 ('며', 1),
 ('피드백', 1),
 ('실사', 1),
 ('수준', 1),
 ('동시', 1),
 ('를', 1),
 ('반영', 1),
 ('수', 1),
 ('모델', 1),
 ('발전', 1),
 ('것', 1),
 ('말', 1)]

In [13]:
word_to_index = { word[0] : index+1 for index,word in enumerate(words_cleaned)}
word_to_index

{'이미지': 1,
 '및': 2,
 '데이터': 3,
 '학습': 4,
 '사용자': 5,
 '생': 6,
 '김일': 7,
 '카카오': 8,
 '브레인': 9,
 '각자': 10,
 '대표': 11,
 '인체': 12,
 '비율': 13,
 '구도': 14,
 '공간': 15,
 '감': 16,
 '입': 17,
 '체감': 18,
 '표현': 19,
 '투시도': 20,
 '등': 21,
 '기술': 22,
 '고도화': 23,
 '과정': 24,
 '칼': 25,
 '며': 26,
 '피드백': 27,
 '실사': 28,
 '수준': 29,
 '동시': 30,
 '를': 31,
 '반영': 32,
 '수': 33,
 '모델': 34,
 '발전': 35,
 '것': 36,
 '말': 37}

In [14]:
sentence = '카카오브레인은 고도화된 기술모델을 가지고 있다.'

sentence_to_index = [word_to_index[word] for word in okt.nouns(sentence) if word in word_to_index]
sentence_to_index

[8, 9, 23, 22, 34]

In [15]:
#keras를 사용한 정수인코딩
from keras.preprocessing.text import Tokenizer


In [18]:
text_data = '''
김일두 카카오브레인 각자 대표는 “인체 비율 및 구도, 공간감과 입체감을 표현하는 투시도 등 다양한 이미지 데이터 학습 및 기술 고도화 과정을 거쳐 칼로 2.0을 선보이게 됐다”며 “많은 데이터와 사용자 피드백을 학습시켜 실사 수준의 이미지를 생성하는 동시에 보다 다양한 사용자의 니즈를 반영할 수 있는 이미지 생성 모델로 발전시켜 나갈 것”이라고 말했다
'''
text = okt.nouns(text_data)
text


['김일',
 '카카오',
 '브레인',
 '각자',
 '대표',
 '인체',
 '비율',
 '및',
 '구도',
 '공간',
 '감',
 '입',
 '체감',
 '표현',
 '투시도',
 '등',
 '이미지',
 '데이터',
 '학습',
 '및',
 '기술',
 '고도화',
 '과정',
 '칼',
 '며',
 '데이터',
 '사용자',
 '피드백',
 '학습',
 '실사',
 '수준',
 '이미지',
 '생',
 '동시',
 '사용자',
 '를',
 '반영',
 '수',
 '이미지',
 '생',
 '모델',
 '발전',
 '것',
 '말']

In [19]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_data)

In [20]:
print(tokenizer.word_index)

{'이': 1, '다': 2, '는': 3, '을': 4, '시': 5, '자': 6, '도': 7, '미': 8, '지': 9, '사': 10, '카': 11, '인': 12, '표': 13, '“': 14, '체': 15, '및': 16, '감': 17, '과': 18, '하': 19, '양': 20, '한': 21, '데': 22, '터': 23, '학': 24, '습': 25, '고': 26, '로': 27, '보': 28, '”': 29, '용': 30, '켜': 31, '수': 32, '의': 33, '를': 34, '생': 35, '성': 36, '김': 37, '일': 38, '두': 39, '오': 40, '브': 41, '레': 42, '각': 43, '대': 44, '비': 45, '율': 46, '구': 47, '공': 48, '간': 49, '입': 50, '현': 51, '투': 52, '등': 53, '기': 54, '술': 55, '화': 56, '정': 57, '거': 58, '쳐': 59, '칼': 60, '2': 61, '0': 62, '선': 63, '게': 64, '됐': 65, '며': 66, '많': 67, '은': 68, '와': 69, '피': 70, '드': 71, '백': 72, '실': 73, '준': 74, '동': 75, '에': 76, '니': 77, '즈': 78, '반': 79, '영': 80, '할': 81, '있': 82, '모': 83, '델': 84, '발': 85, '전': 86, '나': 87, '갈': 88, '것': 89, '라': 90, '말': 91, '했': 92}


In [21]:
sentence = '카카오브레인은 고도화된 기술모델을 가지고 있다.'
st = okt.nouns(sentence)
print(st)
print(tokenizer.texts_to_sequences([st]))

['카카오', '브레인', '고도화', '기술', '모델', '가지']
[[]]


In [22]:
#패딩

import numpy as np
from keras.preprocessing.text import Tokenizer

In [23]:
#정수인코딩 과정을 거침
text_data = '''
과학기술정보통신부는 충청권 4개 지자체와 디지털 기술을 활용한 재난안전관리 시스템을 구축하는 '인공지능(AI)·메타버스 기반 재난안전관리체계 강화' 사업을 추진한다고 9일 밝혔다.

시스템은 메타버스 환경을 통해 사고 징후를 실시간 모니터링 하고, AI 기술로 사고 예방 및 사후 대응을 위한 최적의 의사결정을 지원해 피해규모를 최소화한다.

과기정통부는 디지털 기반의 사고 예방·대응 시스템 개발과 실증을 2025년까지 3년간 지원한다. 올해는 국비 80억원, 지방비 40억원 등 총 120억원을 투입한다.

충청북도에서는 산업단지를 중심으로 화재·폭발 등 대규모 사고 위험이 높은 산업 현장의 안전 강화를 추진한다. 기업별 제조 환경에 따른 맞춤형 고위험 사고 예방·관리 AI 솔루션과 생산 공정 전주기 안전관리 시스템 등을 개발 지원한다.

충청남도에서는 교통사고 다발구역을 대상으로 사고 유발요소를 탐지하는 도로안전 관리 AI 솔루션을 개발한다. 또 인파사고 등을 예방·관리하는 생활안전 관리 AI 솔루션, 공공데이터와 연계한 도로·생활안전 통합관제시스템을 마련한다.
'''
text = okt.nouns(text_data)
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text)

In [24]:
text_data = text_data.replace('\n','')
text_result = text_data.split('.')

text_result

["과학기술정보통신부는 충청권 4개 지자체와 디지털 기술을 활용한 재난안전관리 시스템을 구축하는 '인공지능(AI)·메타버스 기반 재난안전관리체계 강화' 사업을 추진한다고 9일 밝혔다",
 '시스템은 메타버스 환경을 통해 사고 징후를 실시간 모니터링 하고, AI 기술로 사고 예방 및 사후 대응을 위한 최적의 의사결정을 지원해 피해규모를 최소화한다',
 '과기정통부는 디지털 기반의 사고 예방·대응 시스템 개발과 실증을 2025년까지 3년간 지원한다',
 ' 올해는 국비 80억원, 지방비 40억원 등 총 120억원을 투입한다',
 '충청북도에서는 산업단지를 중심으로 화재·폭발 등 대규모 사고 위험이 높은 산업 현장의 안전 강화를 추진한다',
 ' 기업별 제조 환경에 따른 맞춤형 고위험 사고 예방·관리 AI 솔루션과 생산 공정 전주기 안전관리 시스템 등을 개발 지원한다',
 '충청남도에서는 교통사고 다발구역을 대상으로 사고 유발요소를 탐지하는 도로안전 관리 AI 솔루션을 개발한다',
 ' 또 인파사고 등을 예방·관리하는 생활안전 관리 AI 솔루션, 공공데이터와 연계한 도로·생활안전 통합관제시스템을 마련한다',
 '']

In [26]:
encoding_data = []
for temp in text_result:
    temp = temp.strip()
    st = okt.nouns(temp)
    encoding_data.append(tokenizer.texts_to_sequences([st])[0])

print(encoding_data)

[[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35], [4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47], [48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7], [51, 52, 53, 6, 54, 55], [56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17], [63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7], [70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8], [78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84], []]


In [27]:
max_len = max(len(item) for item in encoding_data)
print(max_len)

26


In [29]:
for sentence in encoding_data:
    while len(sentence) < max_len:
        sentence.append(0)
print(encoding_data)

[[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35], [4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47, 0, 0, 0, 0], [48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [51, 52, 53, 6, 54, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7, 0, 0, 0, 0, 0, 0, 0], [70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [30]:
#제로페딩
for sentence in encoding_data:
    print(sentence)

[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35]
[4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47, 0, 0, 0, 0]
[48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[51, 52, 53, 6, 54, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7, 0, 0, 0, 0, 0, 0, 0]
[70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [31]:
#keras - 패딩
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [32]:
text_data = '''
과학기술정보통신부는 충청권 4개 지자체와 디지털 기술을 활용한 재난안전관리 시스템을 구축하는 '인공지능(AI)·메타버스 기반 재난안전관리체계 강화' 사업을 추진한다고 9일 밝혔다.

시스템은 메타버스 환경을 통해 사고 징후를 실시간 모니터링 하고, AI 기술로 사고 예방 및 사후 대응을 위한 최적의 의사결정을 지원해 피해규모를 최소화한다.

과기정통부는 디지털 기반의 사고 예방·대응 시스템 개발과 실증을 2025년까지 3년간 지원한다. 올해는 국비 80억원, 지방비 40억원 등 총 120억원을 투입한다.

충청북도에서는 산업단지를 중심으로 화재·폭발 등 대규모 사고 위험이 높은 산업 현장의 안전 강화를 추진한다. 기업별 제조 환경에 따른 맞춤형 고위험 사고 예방·관리 AI 솔루션과 생산 공정 전주기 안전관리 시스템 등을 개발 지원한다.

충청남도에서는 교통사고 다발구역을 대상으로 사고 유발요소를 탐지하는 도로안전 관리 AI 솔루션을 개발한다. 또 인파사고 등을 예방·관리하는 생활안전 관리 AI 솔루션, 공공데이터와 연계한 도로·생활안전 통합관제시스템을 마련한다.
'''

In [33]:
text = okt.nouns(text_data)

In [34]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text)

In [35]:
encoding_data = []
for temp in text_result:
    temp = temp.strip()
    st = okt.nouns(temp)
    encoding_data.append(tokenizer.texts_to_sequences([st])[0])

print(encoding_data)

[[24, 25, 26, 27, 28, 10, 11, 29, 12, 1, 2, 4, 30, 31, 32, 13, 14, 15, 12, 1, 2, 33, 16, 34, 17, 35], [4, 13, 14, 18, 36, 3, 37, 38, 39, 11, 3, 5, 40, 41, 19, 42, 43, 44, 7, 45, 46, 47], [48, 49, 10, 15, 3, 5, 19, 4, 8, 50, 7], [51, 52, 53, 6, 54, 55], [56, 20, 57, 58, 59, 60, 6, 61, 3, 21, 20, 62, 1, 16, 17], [63, 64, 65, 18, 66, 21, 3, 5, 2, 9, 67, 68, 69, 1, 2, 4, 6, 8, 7], [70, 71, 72, 73, 74, 3, 75, 76, 77, 22, 1, 2, 9, 8], [78, 79, 3, 6, 5, 2, 23, 1, 2, 9, 80, 81, 22, 23, 1, 82, 83, 4, 84], []]


In [36]:
padding = pad_sequences(encoding_data , padding='post',maxlen=10, truncation='post') #truncation하면 maxlen보다 클시 앞부분을 살리고 뒷부분의 데이터를 날림
padding

array([[14, 15, 12,  1,  2, 33, 16, 34, 17, 35],
       [40, 41, 19, 42, 43, 44,  7, 45, 46, 47],
       [49, 10, 15,  3,  5, 19,  4,  8, 50,  7],
       [51, 52, 53,  6, 54, 55,  0,  0,  0,  0],
       [60,  6, 61,  3, 21, 20, 62,  1, 16, 17],
       [ 9, 67, 68, 69,  1,  2,  4,  6,  8,  7],
       [74,  3, 75, 76, 77, 22,  1,  2,  9,  8],
       [ 9, 80, 81, 22, 23,  1, 82, 83,  4, 84],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [37]:
last_value = len(tokenizer.word_index) + 1
last_value

85

In [38]:
padding = pad_sequences(encoding_data, truncating = 'post', padding = 'post', maxlen = 10, value = last_value)
padding

array([[24, 25, 26, 27, 28, 10, 11, 29, 12,  1],
       [ 4, 13, 14, 18, 36,  3, 37, 38, 39, 11],
       [48, 49, 10, 15,  3,  5, 19,  4,  8, 50],
       [51, 52, 53,  6, 54, 55, 85, 85, 85, 85],
       [56, 20, 57, 58, 59, 60,  6, 61,  3, 21],
       [63, 64, 65, 18, 66, 21,  3,  5,  2,  9],
       [70, 71, 72, 73, 74,  3, 75, 76, 77, 22],
       [78, 79,  3,  6,  5,  2, 23,  1,  2,  9],
       [85, 85, 85, 85, 85, 85, 85, 85, 85, 85]], dtype=int32)

In [39]:
#원핫인코딩
# 5  : 0,1,2,3,4
#[ [1,0,0,0,0],[0,0,0,0,1] ]

In [40]:
from konlpy.tag import Okt
okt = Okt()
text_data = okt.morphs('나는 오늘 파이썬을 공부하고 있습니다')
text_data

['나', '는', '오늘', '파이썬', '을', '공부', '하고', '있습니다']

In [41]:
word_encoding = {word : index for index,word in enumerate(text_data)}
print(word_encoding)

{'나': 0, '는': 1, '오늘': 2, '파이썬': 3, '을': 4, '공부': 5, '하고': 6, '있습니다': 7}


In [42]:
one_hot_vector = [0] * (len(word_encoding))
one_hot_vector

[0, 0, 0, 0, 0, 0, 0, 0]

In [43]:
index = word_encoding['파이썬']
index

3

In [44]:
one_hot_vector[index] = 1
one_hot_vector

[0, 0, 0, 1, 0, 0, 0, 0]

In [45]:
#one-hot encoding keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

In [46]:
text = '나는 오늘 파이썬을 공부하고 있습니다.'

tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
tokenizer.word_index

{'나는': 1, '오늘': 2, '파이썬을': 3, '공부하고': 4, '있습니다': 5}

In [47]:
sentence = '나는 오늘 파이썬을 공부하고 있습니다.'
encoded = tokenizer.texts_to_sequences([sentence])[0]
encoded

[1, 2, 3, 4, 5]

In [48]:
one_hot = to_categorical(encoded)
print(one_hot)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
